"""adding diagnosticv to sessions

Revision ID: 4470579d6dbc
Revises: 72c3053d4633
Create Date: 2025-07-14 12:18:24.290158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4470579d6dbc'
down_revision = '72c3053d4633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_document')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('diagnostic')

    op.create_table('session_document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filetype', sa.VARCHAR(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
