"""update nullable fields on Patients

Revision ID: fa50c408f716
Revises: d0bbe2bb3ab2
Create Date: 2025-07-12 19:28:53.212769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa50c408f716'
down_revision = 'd0bbe2bb3ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('phone_number_1',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('phone_number_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('address_2',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('medical_history',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('current_medications',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('allergies',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('emergency_contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('emergency_contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('emergency_contact_relationship',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('emergency_contact_relationship',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('emergency_contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('emergency_contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('allergies',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('current_medications',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('medical_history',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address_2',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone_number_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('phone_number_1',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
