"""empty message

Revision ID: 014af2f691bd
Revises: 9052da6292fc
Create Date: 2025-07-04 17:54:15.906758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014af2f691bd'
down_revision = '9052da6292fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
